[tool.poetry]
name = "digiprod-gen"
version = "0.1.0"
description = "Digital Product Generator is a streamlit app that allows users to create digital products such a Print on Demand (POD) designs."
authors = ["fteutsch <florian.teutsch@inovex.de>"]
readme = "README.md"
packages = [{include = "digiprod_gen"}]

[tool.poetry.dependencies]
python = "^3.10"
llm-few-shot-gen = "^0.0.3"
streamlit = "^1.25.0"
beautifulsoup4 = "^4.12.2"
requests = "^2.31.0"
accelerate = "^0.21.0"
bitsandbytes = "^0.40.2"
openai = "^0.27.8"
opencv-python = "^4.8.0.74"
numpy = "^1.25.1"
langchain = "^0.0.239"
selenium = "^4.10.0"
undetected-chromedriver = "^3.5.0"
seleniumbase = "^4.16.2"
replicate = "^0.9.0"
stability-sdk = "^0.8.4"
click = "^8.1.7"
pydantic-yaml = "^1.1.1"
selenium-wire = "^5.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
start_digiprod_gen = 'digiprod_gen.app:start_digiprod_gen'