MBA_BANNED_WORDS = [
    "t-shirt",
    "t-shirts",
    "tank top",
    "shirt",
    "shirts",
    "tee",
    "tees",
    "gift",
    "gifts",
    "long sleeve",
    "pullover",
    "sweatshirt",
    "hoodie",
]