---
backend:
  host: localhost
  port: 8080
  debug: true
mba:
  marketplaces:
    - marketplace: com
      postcode: "90001"
#      proxy: "dallas.perfect-privacy.com"
#      proxy_port: 3128
    - marketplace: de
      postcode: "10115"
      proxy: "hamburg.perfect-privacy.com"
      proxy_port: 3128
    - marketplace: co.uk
      postcode: "W2 2SZ"
    - marketplace: fr
      postcode: "75001"
      proxy: "hamburg.perfect-privacy.com" # german page viewer can see products offered on france marketplace
      proxy_port: 3128
    - marketplace: es
      postcode: "28001"
    - marketplace: it
      postcode: "00127"
    - marketplace: co.jp
      postcode: "100-0000"
browser:
  selenium_data_dir_path: /tmp/selenium_data
view:
  cards_per_row: 4
image_gen:
  background_removal:
    outer_pixel_range: 10
    tolerance: 30
